name: Sync Leetcode

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: joshcai/leetcode-stnc@v1.7
        with:
          github-token: ${{github.token }}
          leetcode-csrf-token: ${{ secret.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secret.LEETCODE_SESSION }}
          verbose: true
